function deepFreeze(value) {
  if (value === null || typeof value !== 'object' || Object.isFrozen(value)) {
    return value;
  }
  for (const child of Object.values(value)) deepFreeze(child);
  return Object.freeze(value);
}

export const JIANGWAN_OUTDOOR_CITY_PACK = deepFreeze({
  schema: 'lzy-city-pack-v1',
  sceneId: 'jiangwan_outdoor',
  geometryRevision: 'jiangwan-outdoor-v2',
  coordinateScale: 1024,
  saveCompatibility: {
    packVersion: 'jiangwan-outdoor-pack-v2',
    migrationId: 'migrate_jiangwan_outdoor_v2',
    compatibleGeometryRevisions: ['jiangwan-outdoor-v1'],
  },
  runtimeContract: {
    authorityWriter: 'worker_controller',
    progressionBoundary: 'processNextEvent',
    elapsedHistoryReadsPerStep: 0,
    activeComplexityCaps: {
      visibleActors: 32,
      visibleCohorts: 12,
      nearbyOffers: 24,
      dynamicFixtures: 96,
    },
  },
  bounds: { x: 0, y: 0, width: 32_768, height: 24_576 },
  walkBounds: {
    minX: 1_024,
    minY: 1_024,
    maxX: 31_744,
    maxY: 23_552,
  },
  roads: [
    {
      roadId: 'jiangwan_lane',
      widthQ: 4_096,
      centerlineQ: [
        { x: 1_024, y: 18_432 },
        { x: 31_744, y: 18_432 },
      ],
    },
    {
      roadId: 'riverside_road',
      widthQ: 3_072,
      centerlineQ: [
        { x: 1_024, y: 9_216 },
        { x: 25_600, y: 9_216 },
        { x: 25_600, y: 15_360 },
      ],
    },
  ],
  walkableRegions: [
    {
      regionId: 'home_sidewalk',
      x: 1_024,
      y: 19_456,
      width: 11_264,
      height: 2_048,
    },
    {
      regionId: 'market_sidewalk',
      x: 12_288,
      y: 15_360,
      width: 19_456,
      height: 2_048,
    },
    {
      regionId: 'riverside_greenway',
      x: 1_024,
      y: 4_096,
      width: 30_720,
      height: 2_048,
    },
    {
      regionId: 'east_crossing',
      x: 24_576,
      y: 6_144,
      width: 2_048,
      height: 9_216,
    },
    {
      regionId: 'old_port_plaza',
      x: 10_240,
      y: 14_336,
      width: 14_336,
      height: 2_048,
    },
    {
      regionId: 'public_service_sidewalk',
      x: 23_040,
      y: 18_432,
      width: 8_704,
      height: 1_024,
    },
    {
      regionId: 'library_ferry_promontory',
      x: 1_024,
      y: 9_216,
      width: 30_720,
      height: 1_024,
    },
  ],
  colliders: [
    {
      colliderId: 'home_building_shell',
      x: 1_024,
      y: 21_504,
      width: 8_192,
      height: 2_048,
    },
    {
      colliderId: 'breakfast_shop_shell',
      x: 11_264,
      y: 17_408,
      width: 5_120,
      height: 5_120,
    },
    {
      colliderId: 'daily_store_shell',
      x: 17_408,
      y: 17_408,
      width: 5_120,
      height: 5_120,
    },
    {
      colliderId: 'community_service_shell',
      x: 27_648,
      y: 19_456,
      width: 4_096,
      height: 4_096,
    },
    {
      colliderId: 'jiangwan_clinic_shell',
      x: 23_552,
      y: 19_456,
      width: 3_072,
      height: 4_096,
    },
    {
      colliderId: 'jiangwan_library_shell',
      x: 1_024,
      y: 6_144,
      width: 6_144,
      height: 3_072,
    },
    {
      colliderId: 'old_port_market_shell',
      x: 11_264,
      y: 10_240,
      width: 7_168,
      height: 4_096,
    },
    {
      colliderId: 'jiangwan_workshop_shell',
      x: 19_456,
      y: 10_240,
      width: 4_096,
      height: 4_096,
    },
    {
      colliderId: 'riverside_ferry_terminal_shell',
      x: 27_648,
      y: 6_144,
      width: 3_072,
      height: 3_072,
    },
  ],
  anchors: {
    home_arrival: { x: 3_072, y: 19_968 },
    breakfast_door: { x: 13_824, y: 16_896 },
    daily_store_door: { x: 19_968, y: 16_896 },
    riverside_entry: { x: 8_192, y: 5_120 },
    court_entry: { x: 23_552, y: 5_120 },
    bus_stop_wait: { x: 28_672, y: 14_848 },
    clinic_entry: { x: 24_576, y: 18_944 },
    library_entry: { x: 4_096, y: 9_728 },
    old_port_entry: { x: 14_848, y: 14_848 },
    ferry_wait: { x: 29_184, y: 9_728 },
    workshop_entry: { x: 21_504, y: 14_848 },
    property_office_entry: { x: 29_696, y: 18_944 },
  },
  environmentCapabilities: {
    presentationOnly: true,
    authorityBindings: {
      dayPhaseRef: 'world.environment.dayPhase',
      weatherRef: 'world.environment.weather',
      trafficRef: 'world.mobility.activeCohorts',
      footfallRef: 'world.places.activeCohorts',
    },
    dayPhases: [
      {
        phaseId: 'dawn',
        labelZh: '清晨',
        lightingToken: 'city_dawn_soft',
        soundscapeToken: 'jiangwan_waking',
      },
      {
        phaseId: 'day',
        labelZh: '白天',
        lightingToken: 'city_day_neutral',
        soundscapeToken: 'jiangwan_active',
      },
      {
        phaseId: 'dusk',
        labelZh: '傍晚',
        lightingToken: 'city_dusk_warm',
        soundscapeToken: 'jiangwan_evening',
      },
      {
        phaseId: 'night',
        labelZh: '夜间',
        lightingToken: 'city_night_lamps',
        soundscapeToken: 'jiangwan_quiet',
      },
    ],
    weatherProfiles: [
      {
        weatherId: 'clear',
        labelZh: '晴朗',
        surfaceToken: 'pavement_dry',
        particleToken: 'none',
        soundscapeToken: 'clear_air',
        reducedMotionFallback: '保持静态干燥路面与清晰轮廓',
      },
      {
        weatherId: 'overcast',
        labelZh: '阴天',
        surfaceToken: 'pavement_matte',
        particleToken: 'cloud_shadow_soft',
        soundscapeToken: 'muted_street',
        reducedMotionFallback: '使用低对比天空与静态柔光',
      },
      {
        weatherId: 'rain',
        labelZh: '下雨',
        surfaceToken: 'pavement_wet_reflection',
        particleToken: 'rain_streaks',
        soundscapeToken: 'rain_on_city',
        reducedMotionFallback: '隐藏雨丝，仅保留湿地反光与雨声提示',
      },
    ],
  },
  accessibility: {
    inputMethods: ['keyboard', 'touch', 'controller', 'semantic_move_to'],
    reducedMotion: true,
    colorIndependentSemantics: true,
    landmarks: [
      {
        semanticId: 'jiangwan_home_gate',
        labelZh: '江湾住区门厅',
        anchorId: 'home_arrival',
      },
      {
        semanticId: 'morning_tide_breakfast',
        labelZh: '潮生早餐铺',
        anchorId: 'breakfast_door',
      },
      {
        semanticId: 'harbor_daily_store',
        labelZh: '海角日用店',
        anchorId: 'daily_store_door',
      },
      {
        semanticId: 'riverside_walk',
        labelZh: '江湾河畔步道',
        anchorId: 'riverside_entry',
      },
      {
        semanticId: 'community_court',
        labelZh: '江湾社区球场',
        anchorId: 'court_entry',
      },
      {
        semanticId: 'jiangwan_bus_stop',
        labelZh: '江湾里公交站',
        anchorId: 'bus_stop_wait',
      },
      {
        semanticId: 'jiangwan_clinic',
        labelZh: '江湾社区门诊',
        anchorId: 'clinic_entry',
      },
      {
        semanticId: 'jiangwan_library',
        labelZh: '江湾图书馆',
        anchorId: 'library_entry',
      },
      {
        semanticId: 'old_port_market',
        labelZh: '旧港生活集市',
        anchorId: 'old_port_entry',
      },
      {
        semanticId: 'riverside_ferry_pier',
        labelZh: '江湾渡口',
        anchorId: 'ferry_wait',
      },
      {
        semanticId: 'jiangwan_workshop',
        labelZh: '江湾共作间',
        anchorId: 'workshop_entry',
      },
      {
        semanticId: 'jiangwan_property_office',
        labelZh: '江湾住区服务处',
        anchorId: 'property_office_entry',
      },
    ],
  },
  places: [
    {
      placeId: 'jiangwan_home_gate',
      labelZh: '江湾住区门厅',
      kind: 'building_entry',
      anchorId: 'home_arrival',
      useClasses: ['residential', 'portal'],
      portalIds: ['jiangwan_street_to_home'],
      accessPolicyRef: 'access:jiangwan_home',
    },
    {
      placeId: 'morning_tide_breakfast',
      labelZh: '潮生早餐铺',
      kind: 'business_entry',
      anchorId: 'breakfast_door',
      useClasses: ['business', 'food', 'indoor_entry'],
      portalIds: ['street_to_morning_tide_breakfast'],
      operatorRef: 'actor:morning_tide_operator',
      offerBookRef: 'retail:morning_tide_breakfast',
      accessPolicyRef: 'access:morning_tide_breakfast',
    },
    {
      placeId: 'harbor_daily_store',
      labelZh: '海角日用店',
      kind: 'business_entry',
      anchorId: 'daily_store_door',
      useClasses: ['business', 'retail', 'indoor_entry'],
      portalIds: ['street_to_harbor_daily_store'],
      operatorRef: 'actor:harbor_daily_operator',
      offerBookRef: 'retail:harbor_daily_store',
      accessPolicyRef: 'access:harbor_daily_store',
    },
    {
      placeId: 'riverside_walk',
      labelZh: '江湾河畔步道',
      kind: 'outdoor',
      anchorId: 'riverside_entry',
      useClasses: ['entertainment', 'walking', 'social'],
      portalIds: [],
      activityBoardRef: 'activities:riverside_walk',
      accessPolicyRef: 'access:public_outdoor',
    },
    {
      placeId: 'community_court',
      labelZh: '江湾社区球场',
      kind: 'outdoor',
      anchorId: 'court_entry',
      useClasses: ['entertainment', 'sport', 'social'],
      portalIds: [],
      activityBoardRef: 'activities:community_court',
      accessPolicyRef: 'access:community_court',
    },
    {
      placeId: 'jiangwan_bus_stop',
      labelZh: '江湾里公交站',
      kind: 'transit_stop',
      anchorId: 'bus_stop_wait',
      useClasses: ['transit', 'waiting'],
      portalIds: [],
      serviceBoardRef: 'transit:jiangwan_bus_stop',
      accessPolicyRef: 'access:public_transit',
    },
    {
      placeId: 'jiangwan_clinic',
      labelZh: '江湾社区门诊',
      kind: 'service_entry',
      anchorId: 'clinic_entry',
      useClasses: ['health_service', 'appointment', 'indoor_entry'],
      portalIds: [],
      operatorRef: 'actor:jiangwan_clinic_operator',
      serviceBoardRef: 'services:jiangwan_clinic',
      accessPolicyRef: 'access:jiangwan_clinic',
    },
    {
      placeId: 'jiangwan_library',
      labelZh: '江湾图书馆',
      kind: 'public_entry',
      anchorId: 'library_entry',
      useClasses: ['culture', 'entertainment', 'learning', 'indoor_entry'],
      portalIds: [],
      operatorRef: 'actor:jiangwan_library_operator',
      activityBoardRef: 'activities:jiangwan_library',
      accessPolicyRef: 'access:jiangwan_library',
    },
    {
      placeId: 'old_port_market',
      labelZh: '旧港生活集市',
      kind: 'market_entry',
      anchorId: 'old_port_entry',
      useClasses: ['business', 'retail', 'food', 'social'],
      portalIds: [],
      operatorRef: 'actor:old_port_market_operator',
      offerBookRef: 'offers:old_port_market',
      accessPolicyRef: 'access:old_port_market',
    },
    {
      placeId: 'riverside_ferry_pier',
      labelZh: '江湾渡口',
      kind: 'transit_stop',
      anchorId: 'ferry_wait',
      useClasses: ['transit', 'entertainment', 'waterfront'],
      portalIds: [],
      operatorRef: 'actor:jiangwan_ferry_operator',
      serviceBoardRef: 'transit:riverside_ferry_pier',
      accessPolicyRef: 'access:public_transit',
    },
    {
      placeId: 'jiangwan_workshop',
      labelZh: '江湾共作间',
      kind: 'business_entry',
      anchorId: 'workshop_entry',
      useClasses: ['business', 'work', 'craft', 'indoor_entry'],
      portalIds: [],
      operatorRef: 'actor:jiangwan_workshop_operator',
      assetBoardRef: 'assets:jiangwan_workshop_stations',
      accessPolicyRef: 'access:jiangwan_workshop',
    },
    {
      placeId: 'jiangwan_property_office',
      labelZh: '江湾住区服务处',
      kind: 'service_entry',
      anchorId: 'property_office_entry',
      useClasses: ['housing', 'maintenance', 'business', 'indoor_entry'],
      portalIds: [],
      operatorRef: 'actor:jiangwan_property_operator',
      serviceBoardRef: 'services:jiangwan_property_office',
      accessPolicyRef: 'access:jiangwan_property_office',
    },
  ],
  portals: [
    {
      portalId: 'home_to_jiangwan_street',
      kind: 'scene_boundary',
      from: { sceneId: 'jiangwan_home', anchorId: 'door_stand' },
      to: { sceneId: 'jiangwan_outdoor', anchorId: 'home_arrival' },
      requiresAuthorityTransition: true,
    },
    {
      portalId: 'jiangwan_street_to_home',
      kind: 'scene_boundary',
      from: { sceneId: 'jiangwan_outdoor', anchorId: 'home_arrival' },
      to: { sceneId: 'jiangwan_home', anchorId: 'door_stand' },
      requiresAuthorityTransition: true,
    },
    {
      portalId: 'street_to_morning_tide_breakfast',
      kind: 'interior_boundary',
      from: { sceneId: 'jiangwan_outdoor', anchorId: 'breakfast_door' },
      to: {
        sceneId: 'morning_tide_breakfast_interior',
        anchorId: 'public_entry',
      },
      requiresAuthorityTransition: true,
    },
    {
      portalId: 'street_to_harbor_daily_store',
      kind: 'interior_boundary',
      from: { sceneId: 'jiangwan_outdoor', anchorId: 'daily_store_door' },
      to: {
        sceneId: 'harbor_daily_store_interior',
        anchorId: 'public_entry',
      },
      requiresAuthorityTransition: true,
    },
  ],
});
